<?php
return [
    [
        'username' => 'arash',
        'password' => '123',
        'name' => 'آرش',
        'phone' => '09123456789',
        'avatar' => 'images/avatar-01.jpg',
    ],
    [
        'username' => 'kian',
        'password' => '123',
        'name' => 'کیان',
        'phone' => '09123456789',
        'avatar' => 'images/avatar-02.jpg',
    ],
    [
        'username' => 'parsa',
        'password' => '123',
        'name' => 'پارسا',
        'phone' => '09123456789',
        'avatar' => 'images/avatar-03.jpg',
    ],
    [
        'username' => 'nima',
        'password' => '123',
        'name' => 'نیما',
        'phone' => '09123456789',
        'avatar' => 'images/avatar-04.jpg',
    ],
    [
        'username' => 'sohrab',
        'password' => '123',
        'name' => 'سهراب',
        'phone' => '09123456789',
        'avatar' => 'images/avatar-05.jpg',
    ],
    [
        'username' => 'dariush',
        'password' => '123',
        'name' => 'داریوش',
        'phone' => '09123456789',
        'avatar' => 'images/avatar-06.jpg',
    ],
    [
        'username' => 'farhad',
        'password' => '123',
        'name' => 'فرهاد',
        'phone' => '09123456789',
        'avatar' => 'images/avatar-07.jpg',
    ],
    [
        'username' => 'behnam',
        'password' => '123',
        'name' => 'بهنام',
        'phone' => '09123456789',
        'avatar' => 'images/avatar-08.jpg',
    ],
    [
        'username' => 'kamyar',
        'password' => '123',
        'name' => 'کامیار',
        'phone' => '09123456789',
        'avatar' => 'images/avatar-09.jpg',
    ],
    [
        'username' => 'pooya',
        'password' => '123',
        'name' => 'پویا',
        'phone' => '09123456789',
        'avatar' => 'images/avatar-10.jpg',
    ],
];
